server:
  port: 9002

jwt:
  secret: randomsecret

secretPsw: kasdjhfkadhsY776ggTyUU65khaskdjfhYuHAwjñlji

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost

spring:
  main:
    allow-bean-definition-overriding: true
    jackson:
      serialization.FAIL_ON_EMPTY_BEANS: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1035830881982-s2er91ab97g2iugtbnsgi1s8c3scde6v.apps.googleusercontent.com
            client-secret: 9kmkgN04TTo3GvaCXagE0HlW
  datasource:
    url: jdbc:mysql://localhost:3306/clientdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: pacutu.98
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: review-service

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect
management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-headers: "*"
        allowed-methods: "*"
        max-age: 3600
